-- create database
CREATE DATABASE JAVA19_SHOPPING CHAR SET utf8mb4;

-- 001.sql
-- --> ITEM_GROUP, ITEM, SIZE, ITEM_DETAIL
CREATE TABLE IF NOT EXISTS ITEM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MATERIAL VARCHAR(255) NOT NULL,
    BUY_PRICE DECIMAL(10, 2) NOT NULL,
    COLOR VARCHAR(255) NOT NULL,
    ITEM_GROUP_ID INT NOT NULL,
    FOREIGN KEY (ITEM_GROUP_ID) REFERENCES ITEM_GROUP(ID)
);
CREATE TABLE IF NOT EXISTS ITEM_GROUP (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ITEM_DETAIL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ITEM_ID INT NOT NULL,
    SIZE_ID INT NOT NULL,
    AMOUNT INT NOT NULL,
    SALES_PRICE DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID),
    FOREIGN KEY (SIZE_ID) REFERENCES SIZE(ID)
);

CREATE TABLE IF NOT EXISTS [SIZE] (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    KEY VARCHAR(10) NOT NULL,
    GENDER VARCHAR(10) NOT NULL,
    DESC VARCHAR(255) NOT NULL
);





