-- 002.sql
-- --> CUSTOMER
CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);