-- 003.sql
-- --> DEPARTMENT, EMPLOYEE
CREATE TABLE IF NOT EXISTS DEPARTMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS EMPLOYEE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);