-- 004.sqL
-- --> PAYMENT_METHOD, ORDER_STATUS
CREATE TABLE IF NOT EXISTS PAYMENT_METHOD (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESC VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDER_STATUS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESC VARCHAR(255) NOT NULL
);