-- 005.sql
-- --> ORDER, BILL, ORDER_DETAIL, ORDER_STATUS_DETAIL
CREATE TABLE IF NOT EXISTS ORDER_TABLE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DELIVERY_FEE DECIMAL(10, 2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PAYMENT_METHOD_ID INT NOT NULL,
    EMPLOYEE_ID INT,
    CUSTOMER_ID INT NOT NULL,
    FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD(ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);
CREATE TABLE IF NOT EXISTS ORDER_DETAIL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    ITEM_DETAIL_ID INT NOT NULL,
    AMOUNT INT NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDER_TABLE(ID),
    FOREIGN KEY (ITEM_DETAIL_ID) REFERENCES ITEM_DETAIL(ID)
);
CREATE TABLE IF NOT EXISTS ORDER_STATUS_DETAIL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    ORDER_STATUS_ID INT NOT NULL,
    EMPLOYEE_ID INT,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDER_TABLE(ID),
    FOREIGN KEY (ORDER_STATUS_ID) REFERENCES ORDER_STATUS(ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)
);
CREATE TABLE IF NOT EXISTS BILL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOTAL_OF_MONEY DECIMAL(10, 2) NOT NULL,
    ORDER_ID INT NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDER_TABLE(ID)
);
