-- tạo table phòng ban 
DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT 
(
DEPARTMENT_ID INT PRIMARY KEY NOT NULL,
DEPARTMENT_NAME VARCHAR(255) UNIQUE NOT NULL,
MANAGER_ID INT NOT NULL,
START_DATE DATE,
FOREIGN KEY MANAGER_ID REFERENCE EMPLOYEE(EMPLOYEE_ID)
);

DROP TABLE IF EXISTS PROJECTS;
CREATE TABLE PROJECTS 
(
PROJECT_ID INT PRIMARY KEY NOT NULL,
PROJECT_NAME VARCHAR(255) UNIQUE NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
REVENUE DECIMAL(10,2) NOT NULL,
MANAGER_ID INT NOT NULL, 
FOREIGN KEY MANAGER_ID REFERENCES EMPLOYEE(EMPLOYEE_ID) 
);

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE
(
EMPLOYEE_ID INT PRIMARY KEY NOT NULL,
EMPLOYEE_NAME VARCHAR(255) UNIQUE NOT NULL,
ADDRESS VARCHAR(255) NOT NULL,
SALARY DECIMAL(10,2) NOT NULL
);
