-- Patches to CREATE TABLE IF NOT EXISTSs
-- DEPARTMENT, EMPLOYEE
USE java1920_shopping;
-- CREATE TABLE IF NOT EXISTS DEPARTMENT
DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE IF NOT EXISTS DEPARTMENT
(
	`ID` INT PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL
);

ALTER TABLE DEPARTMENT MODIFY COLUMN `NAME` VARCHAR(100) NOT NULL;

-- CREATE TABLE IF NOT EXISTS EMPLOYEE
DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE IF NOT EXISTS EMPLOYEE
(
	`ID` INT,
    `NAME`    VARCHAR(255) NOT NULL,
    `PHONE`   VARCHAR(255) NOT NULL,
    `ADDRESS` VARCHAR(255) NOT NULL,
    `DEPARTMENT_ID` INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);
ALTER TABLE EMPLOYEE MODIFY COLUMN `NAME`    VARCHAR(100) NOT NULL;
ALTER TABLE EMPLOYEE MODIFY COLUMN `PHONE`  VARCHAR(20) NOT NULL;
ALTER TABLE EMPLOYEE MODIFY COLUMN `ADDRESS` VARCHAR(100) NOT NULL;