-- create database
CREATE DATABASE JAVA19_SHOPPING CHAR SET utf8mb4;

-- 001.sql
-- ITEM_GROUP, ITEM, SIZE, ITEM_DETAIL

-- 002.sql
-- CUSTOMER

-- 003.sql
-- DEPARTMENT, EMPLOYEE

-- 004.sqL
-- PAYMENT_METHOD, ORDER_STATUS

-- 005.sql
-- ORDER, BILL, ORDER_DETAIL, ORDER_STATUS_DETAIL