-- disable all fks
SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM BILL;
DELETE FROM CUSTOMER;
DELETE FROM DEPARTMENT;
DELETE FROM EMPLOYEE;
DELETE FROM ITEM;
DELETE FROM ITEM_DETAIL;
DELETE FROM ITEM_GROUP;
DELETE FROM `ORDER`;
DELETE FROM ORDER_DETAIL;
DELETE FROM ORDER_STATUS;
DELETE FROM ORDER_STATUS_DETAIL;
DELETE FROM PAYMENT_METHOD;
DELETE FROM SIZE;

-- enable all fks
SET FOREIGN_KEY_CHECKS = 1;