CREATE TABLE CUSTOMER (
    ID INT ,
    `NAME` VARCHAR(100) NOT NULL,
    `EMAIL` VARCHAR(100) NOT NULL,
    `ADDRESS` VARCHAR(100) NOT NULL,
    `PHONE` VARCHAR(100) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID) -- Không cần thiết đặt tên cho ràng buộc primary CONSTRAINT PK_ITEM_GROUP 
);