INSERT INTO DEPARTMENT(ID, `NAME`)
VALUES(1, 'Phòng Kỹ Thuật'),
	  (2, 'Phòng Bán Hàng');

INSERT INTO DEPARTMENT(ID, `NAME`)
VALUES(3, 'Phòng Bảo Vệ');


INSERT INTO EMPLOYEE(ID,`NAME`,EMAIL,ADDRESS,DEPARTMENT_ID)	
VALUES(11, 'Nhân Viên 11', '123456789', 'Đà Nẵng', 1);

INSERT INTO EMPLOYEE(ID,`NAME`,EMAIL,ADDRESS,DEPARTMENT_ID)	
VALUES(12, 'Nhân Viên 12', '123456789', 'Đà Nẵng', 2);

SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;

DELETE FROM DEPARTMENT WHERE ID =3;