CREATE TABLE KHACHHANG (
    MaKH VARCHAR(10) PRIMARY KEY,
    TenKH NVARCHAR(50), -- Khóa mình sử dụng MySQL không dùng NVARCHAR e nhé, sai cú pháp
    DiaChi NVARCHAR(100),
    SoDT VARCHAR(15),
    MaSoThue VARCHAR(15)
);

CREATE TABLE PHONG (
    MaPhong VARCHAR(10) PRIMARY KEY,
    SoKhachToiDa INT,
    TrangThai NVARCHAR(20),
    MoTa NVARCHAR(100)
);

CREATE TABLE MUCTIENGIO (
    MaTienGio VARCHAR(10) PRIMARY KEY,
    DonGia DECIMAL(10, 2),
    MoTa NVARCHAR(100)
);

CREATE TABLE DICHVU (
    MaDV VARCHAR(10) PRIMARY KEY,
    TenDV NVARCHAR(50),
    DonViTinh NVARCHAR(20),
    DonGia DECIMAL(10, 2)
);

CREATE TABLE HOADON (
    MaHD VARCHAR(10) PRIMARY KEY,
    MaKH VARCHAR(10),
    MaPhong VARCHAR(10),
    MaTienGio VARCHAR(10),
    ThoiGianBatDauSD DATETIME,
    ThoiGianKetThucSD DATETIME,
    TrangThaiHD NVARCHAR(20),
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong),
    FOREIGN KEY (MaTienGio) REFERENCES MUCTIENGIO(MaTienGio)
    -- Thếu UNIQUE cho MaKH, MaPhong, MaTienGio
);

CREATE TABLE CHITIET_SUDUNGDV (
    MaHD VARCHAR(10),
    MaDV VARCHAR(10),
    SoLuong INT,
    PRIMARY KEY (MaHD, MaDV),
    FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
    FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV)
);

--> 4
