-- Patches to creating tables:
-- --> ITEM_GROUP, ITEM, SIZE , ITEM_DETAIL
USE JAVA19_SHOPPING;

-- CONSTRAINT tên ràng buộc: Đây là tên của ràng buộc. 
-- UNIQUE: Đây là loại ràng buộc. Trong trường hợp này, nó là ràng buộc duy nhất (unique)

-- xoá table ITEM_GROUP
DROP TABLE IF EXISTS ITEM_GROUP;
-- create table ITEM_GROUP;
CREATE TABLE ITEM_GROUP 
(
	ID INT,
    `NAME` VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    PHONE INT NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
    -- CONSTRAINT PK_ITEM_GROUP PRIMARY KEY (ID) //không nên/cần đặt tên cho ràng buộc khoá chính
);

ALTER TABLE ITEM_GROUP
ADD COLUMN EMAIL TEXT NOT NULL;

ALTER TABLE ITEM_GROUP
MODIFY COLUMN EMAIL VARCHAR(100) NOT NULL;

ALTER TABLE ITEM_GROUP
MODIFY COLUMN ADDRESS TEXT NOT NULL;

ALTER TABLE ITEM_GROUP
MODIFY COLUMN PHONE VARCHAR(30) NOT NULL;

ALTER TABLE ITEM_GROUP
DROP COLUMN EMAIL;

ALTER TABLE ITEM_GROUP
DROP COLUMN ADDRESS;

ALTER TABLE ITEM_GROUP
DROP COLUMN PHONE;

ALTER TABLE ITEM_GROUP
DROP COLUMN PASSWORD;

-- xoá table item
DROP TABLE IF EXISTS ITEM;
-- create table ITEM;
CREATE TABLE ITEM
(
	ID INT,
    MATERIAL VARCHAR(100) NOT NULL,
    BUY_PRICE FLOAT NOT NULL,
    COLOR VARCHAR(100) NOT NULL,
    ITEM_GROUP_ID INT NOT NULL,-- khoá ngoại không bắt buộc khác null
    PRIMARY KEY (ID),
    CONSTRAINT FK_ITEM_ITEM_GROUP FOREIGN KEY (ITEM_GROUP_ID) REFERENCES ITEM_GROUP(ID) 
);

ALTER TABLE ITEM ADD `NAME` VARCHAR(100) NOT NULL;

-- ALTER TABLE ITEM ADD PRIMARY KEY (ID);

-- xoá table size
DROP TABLE IF EXISTS SIZE;

-- create table size;
CREATE TABLE `size` (
  `ID` int NOT NULL,
  `KEY` varchar(10) NOT NULL,
  `GENDER` bit(1) NOT NULL,
  `DESC` text NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT CHK_SIZE_KEY CHECK (`KEY` IN ('S', 'M', 'L', 'XL', 'XXL')),
  CONSTRAINT CHK_SIZE_GENDER CHECK (`GENDER` IN (0, 1))
);

-- chưa học - thử
TRUNCATE SIZE; -- xoá dữ liệu , xoá bây hết không kiểm tra 
DELETE FROM SIZE;
SELECT * FROM SIZE;
INSERT INTO SIZE VALUES(1, 'S', 0, 'Nữ dưới 50kg');

-- xoá table ITEM_DETAIL
DROP TABLE IF EXISTS ITEM_DETAIL;
-- create table ITEM_DETAIL;
CREATE TABLE ITEM_DETAIL
(
	ID INT,
	AMOUNT INT NOT NULL,
	SALES_PRICE FLOAT NOT NULL,
    ITEM_ID INT NOT NULL,
    SIZE_ID INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UNQ_ITEM_SIZE UNIQUE (ITEM_ID, SIZE_ID),
    CONSTRAINT FK_ITEM_DETAIL_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID),
    CONSTRAINT FK_ITEM_DETAIL_SIZE FOREIGN KEY (SIZE_ID) REFERENCES SIZE(ID)
);

ALTER TABLE ITEM_DETAIL
ADD CONSTRAINT FK_ITEM_DETAIL_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID);
    
