-- Patches to creating tables:
-- --> CUSTOMER
USE JAVA19_SHOPPING;

-- xoá table CUSTOMER
DROP TABLE IF EXISTS CUSTOMER;
-- create table CUSTOMER
CREATE TABLE CUSTOMER
(
	ID INT,
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
	PHONE 	INT NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE CUSTOMER
MODIFY COLUMN ADDRESS TEXT NOT NULL;
ALTER TABLE CUSTOMER
MODIFY COLUMN PHONE VARCHAR(20) NOT NULL;
 