-- Patches to creating tables:
-- --> DEPARTMENT, EMPLOYEE

-- xoá table DEPARTMENT
DROP TABLE IF EXISTS DEPARTMENT;
-- create table DEPARTMENT
CREATE TABLE DEPARTMENT
(
	ID INT,
	NAME VARCHAR(100),
    PRIMARY KEY(ID)
);

ALTER TABLE DEPARTMENT
MODIFY COLUMN NAME VARCHAR(100) NOT NULL;

-- xoá table EMPLOYEE
DROP TABLE IF EXISTS EMPLOYEE;
-- create table EMPLOYEE
CREATE TABLE EMPLOYEE
(
	ID INT,
	NAME VARCHAR(100) NOT NULL,
    PHONE INT NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

ALTER TABLE EMPLOYEE
MODIFY COLUMN PHONE VARCHAR(20) NOT NULL;

ALTER TABLE EMPLOYEE
MODIFY COLUMN ADDRESS TEXT NOT NULL;

-- Đổi tên column và kiểu dữ liệu 
ALTER TABLE EMPLOYEE CHANGE DIACHI ADDRESS TEXT NOT NULL;

