-- Patches to CREATE TABLE IF NOT EXISTS
-- CUSTOMER

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE IF NOT EXISTS CUSTOMER
(
	ID INT,
    `NAME` 	   VARCHAR(255) NOT NULL,
    `EMAIL`    VARCHAR(255) NOT NULL,
    `ADDRESS`  VARCHAR(255) NOT NULL,
    `PHONE`    VARCHAR(20)  NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE CUSTOMER MODIFY COLUMN `NAME` VARCHAR(100) NOT NULL;
ALTER TABLE CUSTOMER MODIFY COLUMN `EMAIL` VARCHAR(100) NOT NULL;
ALTER TABLE CUSTOMER MODIFY COLUMN `ADDRESS`  TEXT NOT NULL;
ALTER TABLE CUSTOMER MODIFY COLUMN `PASSWORD` VARCHAR(300) NOT NULL;