-- Patches to creating tables
-- CUSTOMER

USE java19_shopping;

-- create table CUSTOMER
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER
(
	ID 			INT,
    `NAME` 		VARCHAR(100) NOT NULL,
    `EMAIL` 	VARCHAR(50) NOT NULL,
    `ADDRESS` 	VARCHAR(100) NOT NULL,
    `PHONE` 	VARCHAR(20) NOT NULL,
    `PASSWORD` 	VARCHAR(50) NOT NULL
);

ALTER TABLE CUSTOMER
ADD PRIMARY KEY (ID)
