DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE DEPARTMENT (
    ID INT ,
    `NAME` VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

FK_EMPLOYEE_DEPARTMENTCREATE TABLE EMPLOYEE (
    ID INT ,
    `NAME` VARCHAR(100) NOT NULL,
    `PHONE` VARCHAR(100) NOT NULL,
    `ADDRESS` VARCHAR(100) NOT NULL,
    DEPARTMENT_ID INT ,
    PRIMARY KEY (ID), -- Không cần thiết đặt tên cho ràng buộc primary CONSTRAINT PK_ITEM_GROUP 
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);