-- Patches to creating tables
-- DEPARTMENT, EMPLOYEE

USE java19_shopping;

-- create table DEPARTMENT
DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT
(
	ID 		INT,
    `NAME` 	VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

-- create table EMPLOYEE
DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE
(
	ID 				INT,
    `NAME`			VARCHAR(100) NOT NULL,
    `PHONE`			VARCHAR(20) NOT NULL,
    `ADDRESS` 		VARCHAR(200) NOT NULL,
    `DEPARTMENT_ID` INT NOT NULL,
    CONSTRAINT 		FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID),
    PRIMARY 		KEY (ID)
);