-- Patches to CREATE TABLE IF NOT EXISTSs
-- PAYMENT_METHOD, ORDER_STATUS
USE java1920_shopping;
-- CREATE TABLE IF NOT EXISTS PAYMENT_METHOD
DROP TABLE IF EXISTS PAYMENT_METHOD;
CREATE TABLE IF NOT EXISTS PAYMENT_METHOD
(
	ID INT PRIMARY KEY,
    `DESC` VARCHAR(255) NOT NULL
);
ALTER TABLE PAYMENT_METHOD MODIFY COLUMN `DESC` TEXT NOT NULL;

-- CREATE TABLE IF NOT EXISTS ORDER_STATUS
DROP TABLE IF EXISTS ORDER_STATUS;
CREATE TABLE IF NOT EXISTS ORDER_STATUS
(
	ID INT PRIMARY KEY,
    `DESC` VARCHAR(255) NOT NULL
);
ALTER TABLE ORDER_STATUS MODIFY COLUMN `DESC` TEXT NOT NULL;