CREATE TABLE PAYMENT_METHOD
(
	ID			 	INT,
    DESCRIPT	 	VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ORDER_STATUS
(
	ID			 	INT,
    DESCRIPT	 	VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);